calc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'home')
]

invoice/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import InvoiceListView, createInvoice, generate_PDF, view_PDF


app_name = 'invoice'
urlpatterns = [
    path('invoice-list', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('invoice-delete/<id>', views.delete_invoice, name='invoice-delete')
]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('phsys.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('', include("invoice.urls")),
] 

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

phsys/urls.py
from django.urls import path
from . import views
from django_filters.views import FilterView
from .filters import MedicineFilter,CustomerFilter
#from .views import PurchaseDetailListView
app_name = 'phsys'
urlpatterns = [
    path('', views.register, name = 'register'),
    path('index', views.index, name = 'index'),
    path('index2', views.index2, name = 'index2'),
    path('index3', views.index3, name = 'index3'),
    path('medicine', views.medicine, name = 'medicine'),
    path('users', views.users, name = 'users'),
    path('addmed', views.addmed, name = 'addmed'),
    path('update_med/<str:pk>', views.update_med, name = 'update_med'),
    path('delete_med/<med_id>', views.delete_med, name = 'delete_med'),
    path('delete_cus/<cus_id>', views.delete_cus, name = 'delete_cus'),
    path('delete_purchase/<purchase_id>', views.delete_purchase, name = 'delete_purchase'),
    path('delete_user/<usname>', views.delete_user, name = 'delete_user'),
    path('delete_sale/<sale_id>', views.delete_sale, name = 'delete_sale'),
    path('delete_manu/<party_id>', views.delete_manu, name = 'delete_manu'),
    path('update_cus/<str:pk>', views.update_cus, name = 'update_cus'),
    path('update_manu/<str:pk>', views.update_manu, name = 'update_manu'),
    path('customer', views.customer, name = 'customer'),
    path('addcus', views.addcus, name = 'addcus'),
    path('addpurchase', views.addpurchase, name = 'addpurchase'),
    path('addmanu', views.addmanu, name = 'addmanu'),
    path('addsale', views.addsale, name = 'addsale'),
    path('adduser', views.adduser, name = 'adduser'),
    path('purchase', views.purchase, name = 'purchase'),
    path('purchase-detail/<id>', views.purchasedetail_trial, name='purchase-detail'),
    path('purchase-download/<id>', views.generate_PDF_purchase, name='purchase-download'),
    path('med-download', views.generate_PDF_med, name='med-download'),
    path('sale', views.sale, name = 'sale'),
    path('sale-detail/<id>', views.saledetail_trial, name='sale-detail'),
    path('sale-download/<id>', views.generate_PDF_sale, name='sale-download'),
    path('receipt-download/<id>', views.generate_PDF_receipt, name='receipt-download'),
    path('searchmed', FilterView.as_view(filterset_class=MedicineFilter,
        template_name='searchmed.html'), name = 'search_med'),
    path('searchcus', FilterView.as_view(filterset_class=CustomerFilter,
        template_name='searchcus.html'), name = 'search_cus'),
    path('manufacturer', views.manufacturer, name = 'manufacturer'),
    path('payment', views.payment, name = 'payment'),
    path('receipt', views.receipt, name = 'receipt'),
    path('receipt_pdf', views.receipt_pdf, name = 'receipt_pdf'),
    path("logout", views.logout_request, name="logout"),
    #path('purchasedetail-list', PurchaseDetailListView.as_view(), name="purchasedetail-list"),
]

invoice/models.py
from django.db import models
import datetime
# Create your models here.
class Invoice(models.Model):
    customer = models.CharField(max_length=100)
    customer_email = models.EmailField(null=True, blank=True)
    billing_address = models.TextField(null=True, blank=True)
    date = models.DateField()
    due_date = models.DateField(null=True, blank=True)
    message = models.TextField(default= "this is a default message.")
    total_amount = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
    status = models.BooleanField(default=False)
    def __str__(self):
        return str(self.customer)
    
    def get_status(self):
        return self.status

    # def save(self, *args, **kwargs):
        # if not self.id:             
        #     self.due_date = datetime.datetime.now()+ datetime.timedelta(days=15)
        # return super(Invoice, self).save(*args, **kwargs)

class LineItem(models.Model):
    customer = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    service = models.TextField()
    description = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=9, decimal_places=2)
    amount = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return str(self.customer)
   
class InvoiceInvoice(models.Model):
    customer = models.CharField(max_length=100)
    date = models.DateField()
    due_date = models.DateField(blank=True, null=True)
    message = models.TextField()
    billing_address = models.TextField(blank=True, null=True)
    customer_email = models.CharField(max_length=254, blank=True, null=True)
    status = models.IntegerField()
    total_amount = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'invoice_invoice'


class InvoiceLineitem(models.Model):
    service = models.TextField()
    description = models.TextField()
    quantity = models.IntegerField()
    rate = models.DecimalField(max_digits=6, decimal_places=2)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    customer = models.ForeignKey(InvoiceInvoice, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'invoice_lineitem'

invoice/forms.py
from django import forms
from django.forms import formset_factory
from .models import Invoice
class InvoiceForm(forms.Form):
    
        # fields = ['customer', 'message']
    customer = forms.CharField(
        label='Cusomter',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Customer/Company Name',
            'rows':1
        })
    )
    customer_email = forms.CharField(
        label='Customer Email',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'customer@company.com',
            'rows':1
        })
    )
    billing_address = forms.CharField(
        label='Billing Address',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '',
            'rows':1
        })
    )
    message = forms.CharField(
        label='Message/Note',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'message',
            'rows':1
        })
    )

class LineItemForm(forms.Form):
    
    service = forms.CharField(
        label='Service/Product',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Service Name'
        })
    )
    description = forms.CharField(
        label='Description',
        widget=forms.TextInput(attrs={
            'class': 'form-control input',
            'placeholder': 'Enter Book Name here',
            "rows":1
        })
    )
    quantity = forms.IntegerField(
        label='Qty',
        widget=forms.TextInput(attrs={
            'class': 'form-control input quantity',
            'placeholder': 'Quantity'
        }) #quantity should not be less than one
    )
    rate = forms.DecimalField(
        label='Rate $',
        widget=forms.TextInput(attrs={
            'class': 'form-control input rate',
            'placeholder': 'Rate'
        })
    )
    # amount = forms.DecimalField(
    #     disabled = True,
    #     label='Amount $',
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control input',
    #     })
    # )
    
LineItemFormset = formset_factory(LineItemForm, extra=1)

invoice/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse
from django.views import View
from .models import LineItem, Invoice
from .forms import LineItemFormset, InvoiceForm
from phsys.decorators import allowed_users
import pdfkit
from weasyprint import HTML, CSS
from django.template.loader import get_template
from pathlib import Path
import os
BASE_DIR = Path(__file__).resolve().parent.parent

class InvoiceListView(View):
    def get(self, *args, **kwargs):
        invoices = Invoice.objects.all()
        context = {
            "invoices":invoices,
        }

        return render(self.request, 'invoice/invoice-list.html', context)

    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice_ids = request.POST.getlist("invoice_id")
        invoice_ids = list(map(int, invoice_ids))

        update_status_for_invoices = int(request.POST['status'])
        invoices = Invoice.objects.filter(id__in=invoice_ids)
        # import pdb;pdb.set_trace()
        if update_status_for_invoices == 0:
            invoices.update(status=False)
        else:
            invoices.update(status=True)

        return redirect('invoice:invoice-list')
@allowed_users(allowed_roles=['Admin','Manager'])
def createInvoice(request):
    """
    Invoice Generator page it will have Functionality to create new invoices,
    this will be protected view, only admin has the authority to read and make
    changes here.
    """

    heading_message = 'Formset Demo'
    if request.method == 'GET':
        formset = LineItemFormset(request.GET or None)
        form = InvoiceForm(request.GET or None)
    elif request.method == 'POST':
        formset = LineItemFormset(request.POST)
        form = InvoiceForm(request.POST)

        if form.is_valid():
            invoice = Invoice.objects.create(customer=form.data["customer"],
                    customer_email=form.data["customer_email"],
                    billing_address = form.data["billing_address"],
                    date=form.data["date"],
                    due_date=form.data["due_date"],
                    message=form.data["message"],
                    )
            # invoice.save()

        if formset.is_valid():
            # import pdb;pdb.set_trace()
            # extract name and other data from each form and save
            total = 0
            for form in formset:
                service = form.cleaned_data.get('service')
                description = form.cleaned_data.get('description')
                quantity = form.cleaned_data.get('quantity')
                rate = form.cleaned_data.get('rate')
                if service and description and quantity and rate:
                    amount = float(rate)*float(quantity)
                    total += amount
                    LineItem(customer=invoice,
                            service=service,
                            description=description,
                            quantity=quantity,
                            rate=rate,
                            amount=amount).save()
            invoice.total_amount = total
            invoice.save()
            try:
                generate_PDF(request, id=invoice.id)
            except Exception as e:
                print(f"********{e}********")
            return redirect('invoice:invoice-list')
    context = {
        "title" : "Invoice Generator",
        "formset": formset,
        "form": form,
    }
    return render(request, 'invoice/invoice-create.html', context)


def view_PDF(request, id=None):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "DB Project",
            "address" :"University of Engineering and Technology, Lahore",
            "phone": "(+92) XXX XXXX",
            "email": "contact@xyz.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        "due_date": invoice.due_date,
        "billing_address": invoice.billing_address,
        "message": invoice.message,
        "lineitem": lineitem,
    }
    return render(request, 'invoice/pdf_template.html', context)

def generate_PDF(request, id):
    invoice = get_object_or_404(Invoice, id=id)
    lineitem = invoice.lineitem_set.all()

    context = {
        "company": {
            "name": "DB Project",
            "address" :"University of Engineering and Technology, Lahore",
            "phone": "(+92) XXX XXXX",
            "email": "contact@xyz.com",
        },
        "invoice_id": invoice.id,
        "invoice_total": invoice.total_amount,
        "customer": invoice.customer,
        "customer_email": invoice.customer_email,
        "date": invoice.date,
        "due_date": invoice.due_date,
        "billing_address": invoice.billing_address,
        "message": invoice.message,
        "lineitem": lineitem,
    }
    # Use False instead of output path to save pdf to a variable
    html_template = get_template('/home/Mahnoorkh/dpharmacy/invoice/templates/invoice/pdf_template.html').render(context)
    pdf_file = HTML(string=html_template).write_pdf(stylesheets=[CSS(os.path.join(BASE_DIR, 'static/css/invoice-template-1.css')),
                                                                 CSS(os.path.join(BASE_DIR, 'static/img/uetlogo.png')),
                                                                 CSS(string='@page { size: A3; margin: 1cm }')])
    response = HttpResponse(pdf_file, content_type='application/pdf')
    response['Content-Disposition'] = 'filename="invoice.pdf"'
    return response

    return response

@allowed_users(allowed_roles=['Admin','Manager'])
def delete_invoice(request,id):
    d_inv=Invoice.objects.get(pk=id)
    d_inv.delete()
    return redirect('invoice:invoice-list')

def change_status(request):
    return redirect('invoice:invoice-list')

def view_404(request,  *args, **kwargs):

    return redirect('invoice:invoice-list')

invoice/templates/invoice/base.html
<!doctype html>{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
     {% block custom_css %}{% endblock %}
    <title>Django Library App</title>
</head>
<body>
     
    <div class="container">
                {% block content %}
                {% endblock %}
            </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     {% block custom_js %}{% endblock %}
</body>

invoice/templates/invoice/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Sidebar 05</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <link href= 'https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900' rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
	.caret {
	  cursor: pointer;
	  -webkit-user-select: none; /* Safari 3.1+ */
	  -moz-user-select: none; /* Firefox 2+ */
	  -ms-user-select: none; /* IE 10+ */
	  user-select: none;
	}

	.fa-angle-left{
	  transform: rotate(0deg);
	}

	.notokay{
	  transform: rotate(-90deg);  
	}

	.treeview-menu {
	  display: none;
	}

	.active {
	  display: block;
	}

	p.logout{
		font-size: 18px;
		color: #dfdfdf;
	}

	i.online{
		color: #dfdfdf;
	}
	</style>
  </head>
  <body>
		
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="custom-menu">
					<button type="button" id="sidebarCollapse" class="btn btn-primary">
	          <i class="fa fa-bars"></i>
	          <span class="sr-only">Toggle Menu</span>
	        </button>
        </div>
				<div class="p-4">
		  		<center><h1><a href="#" class="logo">User<br><span><i class="fa fa-circle text-success online" style='transform: scale(0.5);'></i>Online</span></center></a>
	        <ul class="list-unstyled components mb-5">

	    <!-- Home  -->   	

	          <li class="active">
	            <a href="{%url 'phsys:index' %}"><span class="fa fa-home mr-3"></span>Home</a>
	          </li>

		<!-- Invoice  -->

	          <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-balance-scale mr-3" >
						</span>Invoice
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="{% url 'invoice:invoice-create' %}">New Invoice</a></li>
						{% endif %}
						<li class="treeview  "><a href="{% url 'invoice:invoice-list' %}">Manage Invoice </a></li>
					</ul>
			  </li>
		
		<!-- Customer  -->

			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-user mr-3" >
						</span>Customer
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="addcus">Add Customer</a></li>
						{% endif %}
						<li class="treeview  "><a href="customer">Manage Customer </a></li>
					</ul>
			  </li>

		<!-- Medicine  -->

			  <li class="treeview">
					<a class = 'caret'>
						<span class="fas fa-pills mr-3" >
						</span>Medicine
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="addmed">Add Medicine</a></li>
						{% endif %}
						<li class="treeview  "><a href="medicine">Manage Medicine</a></li>
					</ul>
			  </li>

		<!-- Manufacturer  -->
		      {% if request.user.is_staff %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-user mr-3" >
						</span>Manufacturer
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="addmanu">Add Manufacturer</a></li>
						<li class="treeview  "><a href="manufacturer">Manage Manufacturer</a></li>
					</ul>
			  </li>
			  {% endif %}

		<!-- Purchase  -->
		      {% if request.user.is_staff %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fas fa-cart-plus mr-3" >
						</span>Purchase
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="addpurchase">Add Purchase</a></li>
						<li class="treeview  "><a href="purchase">Manage Purchase</a></li>
					</ul>
			  </li>
			  {% endif %}

		<!-- Sale  -->
		      
			  <li class="treeview">
					<a class = 'caret'>
						<span class="far fa-money-bill-alt mr-3" >
						</span>Sale
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="#">Add Sale</a></li>
						<li class="treeview  "><a href="sale">Manage Sale</a></li>
					</ul>
			  </li>
			  

		<!-- Report  -->

			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-file-text-o mr-3" >
						</span>Report
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="#">Sales Report</a></li>
						<li class="treeview  "><a href="#">Purchase Report</a></li>
					</ul>
			  </li>

		<!-- Payment  -->

			  <li>
	              <a href="#"><span class="	far fa-credit-card mr-3"></span> Payment</a>
	          </li>

	    <!-- Search  -->
		      
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-search mr-3" >
						</span>Search
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="searchmed">Medicine</a></li>
						<li class="treeview  "><a href="searchcus">Customer</a></li>
					</ul>
			  </li>

		<!-- Settings  -->
		      {% if request.user.is_superuser %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-wrench mr-3" >
						</span>Settings
						<i class="fa fa-angle-left pull-right"></i>
					</a>
					<ul class="treeview-menu">

					<!-- Users  -->
						
					<li class="treeview  ">
					<a class = 'caret'>Users
					<i class="fa fa-angle-left pull-right"></i>
					</a>
					<ul class="treeview-menu">
					<li class="treeview  "><a href="#">Add User</a></li>
					<li class="treeview  "><a href="#">Manage Users</a></li>
					</ul>
					</li>

			
			  </li>
			  {% endif %}


			  <script>
				var toggler = document.getElementsByClassName("caret");
				var i;

				for (i = 0; i < toggler.length; i++) {
				  toggler[i].addEventListener("click", function() {
				    this.parentElement.querySelector(".treeview-menu").classList.toggle("active");
				    this.parentElement.querySelector(".fa-angle-left").classList.toggle("notokay");
				  });
				}


			  </script>

		
	        </ul>
	          <a href="logout"><p class='logout'>Logout</p></a>
	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5 pt-5">
      

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

invoice/templates/invoice/invoice-list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
</html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <link href="{% static 'css/bulma-calendar.min.css' %}" rel="stylesheet">
     <link href="{% static 'js/bulma-calendar.min.js' %}" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <style>

    .right {
      position: absolute;
      right: 40px;
    }

    .btn-work {
        width: 150px;
        height: 50px;
        margin: 0 auto;
        vertical-align: middle;
        text-align: center; 
        color:white;
    }

    .btn-work1 {
        width: 100px;
        height: 50px;
        margin: 0 auto;
        vertical-align: middle;
        text-align: center; 
    }

    .btn-work2  {
        display: flex;
        align-items: center;
        justify-content: center;
        position:relative; 
        top:-6px;
    }

    .button {
      background-color: #4CAF50; /* Green */
      border: none;
      color: white;
      padding: 14px 25px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      font-size: 16px;
      margin: 4px 2px;
      transition-duration: 0.4s;
      cursor: pointer;
    }

    .button5 {
      border-radius: 4px;
      background-color: #fff;
      color: white;
      text-align: center;
      
    }

    .button5:hover {
      border-radius: 4px;
      background-color: grey;
      color: blue;
      border: 2px #555555;
      text-align: center;
    }

    </style>
    <meta charset="UTF-8">
    <title>Medicine List</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
<form action="{% url 'invoice:invoice-list' %}" method="post">{% csrf_token %}<br>
    <h1>Invoice List</h1>
    <a href="{% url 'invoice:invoice-create' %}"><button class=" button5 right btn-work ">Create Invoice</a></button>
    <br>
    <br>
    <br>
    <table class="table table-striped table-bordered table-sm">
        <thread class= "thread-dark">
            <tr>
                <th></th>
                <th>INVOICE</th>
                <th>CUSTOMER</th>
                <th>DATE</th>
                <th>DUE DATE</th>
                <th>BALANCE</th>
                <th>TOTAL</th>
                <th>STATUS</th>
                <th>View</th>
                <th>DOWNLOAD</th>
                <th>REMOVE</th>


            </tr>
        </thead>
            {% for invoice in invoices %}
            <tr>
                <td><input class="checkbox" type="checkbox" value="{{invoice.id}}" name="invoice_id" size="1" />
                </td>
                <td width="1%">#{{invoice.id}}</td>
                <td width="9%">{{invoice.customer}}</td>
                <td> {{invoice.date}}</td>
                <td> {{invoice.due_date}} </td>
                <td width="1%"></td>
                <td>{{invoice.total_amount}}</td>
                <td class="level-right">
                    {% if invoice.get_status %}
                    <a class="button is-small is-success btn-work1" href="#">Paid</a>
                    {% else %}
                    <a class="button is-small is-warning btn-work1" href="#">Not Paid</a>
                    {% endif %}
                </td>
                <td width="1%"><a href="{% url 'invoice:invoice-detail' id=invoice.id %}">
                    <div class="button is-small is-info btn-work1">View</div>
                </a></td>
                <td width="1%"><a href="{% url 'invoice:invoice-download' id=invoice.id %}">Download</a></td>
                <td>
                    <a href="{% url 'invoice:invoice-delete' id=invoice.id %}" class='btn btn-danger'>X</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>

            <div class="select is-rounded">
                <select id="status" name="status">
                    <option value="1">Paid</option>
                    <option value="0">Not Paid</option>
                </select>
            </div>
            <input class="button is-info is-rounded btn-work2" type="submit" value="Change Status" name="mybtn">

</form>
</body>