calc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'home')
]

invoice/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import InvoiceListView, createInvoice, generate_PDF, view_PDF


app_name = 'invoice'
urlpatterns = [
    path('invoice-list', InvoiceListView.as_view(), name="invoice-list"),
    path('create/', createInvoice, name="invoice-create"),
    path('invoice-detail/<id>', view_PDF, name='invoice-detail'),
    path('invoice-download/<id>', generate_PDF, name='invoice-download'),
    path('invoice-delete/<id>', views.delete_invoice, name='invoice-delete')
]

pharmacy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('phsys.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('', include("invoice.urls")),
] 

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

phsys/urls.py
from django.urls import path
from . import views
from django_filters.views import FilterView
from .filters import MedicineFilter,CustomerFilter
#from .views import PurchaseDetailListView
app_name = 'phsys'
urlpatterns = [
    path('', views.register, name = 'register'),
    path('index', views.index, name = 'index'),
    path('index2', views.index2, name = 'index2'),
    path('index3', views.index3, name = 'index3'),
    path('medicine', views.medicine, name = 'medicine'),
    path('users', views.users, name = 'users'),
    path('addmed', views.addmed, name = 'addmed'),
    path('update_med/<str:pk>', views.update_med, name = 'update_med'),
    path('delete_med/<med_id>', views.delete_med, name = 'delete_med'),
    path('delete_cus/<cus_id>', views.delete_cus, name = 'delete_cus'),
    path('delete_purchase/<purchase_id>', views.delete_purchase, name = 'delete_purchase'),
    path('delete_user/<usname>', views.delete_user, name = 'delete_user'),
    path('delete_sale/<sale_id>', views.delete_sale, name = 'delete_sale'),
    path('delete_manu/<party_id>', views.delete_manu, name = 'delete_manu'),
    path('update_cus/<str:pk>', views.update_cus, name = 'update_cus'),
    path('update_manu/<str:pk>', views.update_manu, name = 'update_manu'),
    path('customer', views.customer, name = 'customer'),
    path('addcus', views.addcus, name = 'addcus'),
    path('addpurchase', views.addpurchase, name = 'addpurchase'),
    path('addmanu', views.addmanu, name = 'addmanu'),
    path('addsale', views.addsale, name = 'addsale'),
    path('adduser', views.adduser, name = 'adduser'),
    path('purchase', views.purchase, name = 'purchase'),
    path('purchase-detail/<id>', views.purchasedetail_trial, name='purchase-detail'),
    path('purchase-download/<id>', views.generate_PDF_purchase, name='purchase-download'),
    path('med-download', views.generate_PDF_med, name='med-download'),
    path('sale', views.sale, name = 'sale'),
    path('sale-detail/<id>', views.saledetail_trial, name='sale-detail'),
    path('sale-download/<id>', views.generate_PDF_sale, name='sale-download'),
    path('receipt-download/<id>', views.generate_PDF_receipt, name='receipt-download'),
    path('searchmed', FilterView.as_view(filterset_class=MedicineFilter,
        template_name='searchmed.html'), name = 'search_med'),
    path('searchcus', FilterView.as_view(filterset_class=CustomerFilter,
        template_name='searchcus.html'), name = 'search_cus'),
    path('manufacturer', views.manufacturer, name = 'manufacturer'),
    path('payment', views.payment, name = 'payment'),
    path('receipt', views.receipt, name = 'receipt'),
    path('receipt_pdf', views.receipt_pdf, name = 'receipt_pdf'),
    path("logout", views.logout_request, name="logout"),
    #path('purchasedetail-list', PurchaseDetailListView.as_view(), name="purchasedetail-list"),
]

templates/customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
</html>

<head>
	<style>
	
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;
	  
	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Customer List</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
	<span><br>
	<h1>Customer List</h1>
	<a href="addcus"><button class="button button5 right">New Customer</button></a>
	</span>
	<br>
	<br>
	<br>
	<table class="table table-striped table-bordered table-sm">
	<thread class= "thread-dark">
	<tr>
		<th>Customer ID</th>
		<th>Customer Name</th>
		<th>Customer Address</th>
		<th>Customer Contact</th>
		<th>Customer Email</th>
		<th>Action</th>
	</tr>
	</thread>
	{% for cus in customer %}
	<tr>
		<td>{{ cus.cusid }}</td>
		<td>{{ cus.cus_name }}</td>
		<td>{{ cus.cus_address }}</td>
		<td>{{ cus.cus_contact }}</td>
		<td>{{ cus.cus_email }}</td>
		<td>
			<a href="{% url 'phsys:update_cus' cus.cusid %}"><span class="btn btn-success">Edit</span></a>
			<a href="{% url 'phsys:delete_cus' cus.cusid %}" class='btn btn-danger'>Delete</a>
		</td>
	</tr>
{% endfor %}
	<tbody> 

</body>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Sidebar 05</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>

    <link href= 'https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900' rel="stylesheet">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<style>
	.caret {
	  cursor: pointer;
	  -webkit-user-select: none; /* Safari 3.1+ */
	  -moz-user-select: none; /* Firefox 2+ */
	  -ms-user-select: none; /* IE 10+ */
	  user-select: none;
	}

	.fa-angle-left{
	  transform: rotate(0deg);
	}

	.notokay{
	  transform: rotate(-90deg);  
	}

	.treeview-menu {
	  display: none;
	}

	.active {
	  display: block;
	}

	p.logout{
		font-size: 18px;
		color: #dfdfdf;
	}

	i.online{
		color: #dfdfdf;
	}
	</style>
  </head>
  <body>
		
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar">
				<div class="custom-menu">
					<button type="button" id="sidebarCollapse" class="btn btn-primary">
	          <i class="fa fa-bars"></i>
	          <span class="sr-only">Toggle Menu</span>
	        </button>
        </div>
				<div class="p-4">
		  		<center><h1><a href="#" class="logo">{{request.user.first_name}}<br>
	  			{% for group in request.user.groups.all %}
			    {% if group.name == 'Admin' %}
			        <small><small><p>(Admin)</p></small></small>
			    {% elif group.name == 'Manager' %}
			        <small><small><p>(Manager)</p></small></small>
			    {% elif group.name == 'Sales Person' %}
			        <small><small><p>(Sales Person)</p></small></small>
			    {% endif %}
				{% endfor %}<span><i class="fa fa-circle text-success online" style='transform: scale(0.5);'></i>Online</span></center></a>
	        <ul class="list-unstyled components mb-5">

	    <!-- Home  -->   	

	          <li class="active">
	            <a href="{%url 'phsys:index' %}"><span class="fa fa-home mr-3"></span>Home</a>
	          </li>

		<!-- Invoice  -->

	          <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-balance-scale mr-3" >
						</span>Invoice
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="{% url 'invoice:invoice-create' %}">New Invoice</a></li>
						{% endif %}
						<li class="treeview  "><a href="{% url 'invoice:invoice-list' %}">Manage Invoice </a></li>
					</ul>
			  </li>
		
		<!-- Customer  -->

			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-user mr-3" >
						</span>Customer
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="addcus">Add Customer</a></li>
						{% endif %}
						<li class="treeview  "><a href="customer">Manage Customer </a></li>
					</ul>
			  </li>

		<!-- Medicine  -->

			  <li class="treeview">
					<a class = 'caret'>
						<span class="fas fa-pills mr-3"><script src='https://kit.fontawesome.com/a076d05399.js'></script>
						</span>Medicine
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						{% if request.user.is_staff %}
						<li class="treeview  "><a href="addmed">Add Medicine</a></li>
						{% endif %}
						<li class="treeview  "><a href="medicine">Manage Medicine</a></li>
					</ul>
			  </li>

		<!-- Manufacturer  -->
		      {% if request.user.is_staff %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-user mr-3" >
						</span>Manufacturer
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="addmanu">Add Manufacturer</a></li>
						<li class="treeview  "><a href="manufacturer">Manage Manufacturer</a></li>
					</ul>
			  </li>
			  {% endif %}

		<!-- Purchase  -->
		      {% if request.user.is_staff %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fas fa-cart-plus mr-3" >
						</span>Purchase
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="addpurchase">Add Purchase</a></li>
						<li class="treeview  "><a href="purchase">Manage Purchase</a></li>
					</ul>
			  </li>
			  {% endif %}

		<!-- Sale  -->
		      
			  <li class="treeview">
					<a class = 'caret'>
						<span class="far fa-money-bill-alt mr-3" >
						</span>Sale
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="addsale">Add Sale</a></li>
						<li class="treeview  "><a href="sale">Manage Sale</a></li>
					</ul>
			  </li>
			  
		<!-- Payment  -->

			  <li>
	              <a href="payment"><span class="	far fa-credit-card mr-3"></span> Payment</a>
	          </li>

	    <!-- Search  -->
		      
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-search mr-3" >
						</span>Search
						<i class="fa fa-angle-left pull-right">
						</i>
					</a>
					<ul class="treeview-menu">
						<li class="treeview  "><a href="searchmed">Medicine</a></li>
						<li class="treeview  "><a href="searchcus">Customer</a></li>
					</ul>
			  </li>

		<!-- Settings  -->
		      {% if request.user.is_superuser %}
			  <li class="treeview">
					<a class = 'caret'>
						<span class="fa fa-wrench mr-3" >
						</span>Settings
						<i class="fa fa-angle-left pull-right"></i>
					</a>
					<ul class="treeview-menu">

					<!-- Users  -->
						
					<li class="treeview  ">
					<a class = 'caret'>Users
					<i class="fa fa-angle-left pull-right"></i>
					</a>
					<ul class="treeview-menu">
					<li class="treeview  "><a href="adduser">Add User</a></li>
					<li class="treeview  "><a href="users">Manage Users</a></li>
					</ul>
					</li>

			
			  </li>
			  {% endif %}


			  <script>
				var toggler = document.getElementsByClassName("caret");
				var i;

				for (i = 0; i < toggler.length; i++) {
				  toggler[i].addEventListener("click", function() {
				    this.parentElement.querySelector(".treeview-menu").classList.toggle("active");
				    this.parentElement.querySelector(".fa-angle-left").classList.toggle("notokay");
				  });
				}


			  </script>

		
	        </ul>
	          <a href="logout"><p class='logout'>Logout</p></a>
	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5 pt-5">
        

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/manufacturer.html
<!DOCTYPE html>
<html lang="en">
</html>

<head>
	<style>
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;
	  
	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Customer List</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
	
	<span><br>
	<h1>Manufacturer List</h1>
	<a href="addmanu"><button class="button button5 right">New Manufacturer</button></a>
	</span>
	<br>
	<br>
	<br>
	<table class="table table-striped table-bordered table-sm">
	<thread class= "thread-dark">
	<tr>
		<th>Manufacturer ID</th>
		<th>Manufacturer Name</th>
		<th>Manufacturer Address</th>
        <th>Manufacturer Contact</th>
        <th>Action</th>
	</tr>
	</thread>
	{% for cus in parties %}
	<tr>
		<td>{{ cus.party_id }}</td>
		<td>{{ cus.par_name }}</td>
		<td>{{ cus.par_address }}</td>
		<td>{{ cus.contact }}</td>
		<td>
		   <!--<a href="{% url 'phsys:update_manu' cus.party_id %}"><span class="btn btn-success">Edit</span></a>--> 
			<a href="{% url 'phsys:delete_manu' cus.party_id %}" class='btn btn-danger'>Delete</a>
		</td>
	</tr>
{% endfor %}
	<tbody> 
</body>

templates/medicine.html
{% load static %}
<!doctype html>
<!DOCTYPE html>
<html lang="en">
</html>

<head>
 <head>
	<style>
	.caret {
	  cursor: pointer;
	  -webkit-user-select: none; /* Safari 3.1+ */
	  -moz-user-select: none; /* Firefox 2+ */
	  -ms-user-select: none; /* IE 10+ */
	  user-select: none;
	}

	.fa-angle-left{
	  transform: rotate(0deg);
	}

	.notokay{
	  transform: rotate(-90deg);
	}

	.treeview-menu {
	  display: none;
	}
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;

	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Medicine List</title>
	<script src='https://kit.fontawesome.com/a076d05399.js'></script>
	<link href= 'https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900' rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
    <span><br>
	<center><h1 class="text-secondary">Medicine List</h1></center>
	<a href="addmed"><button class="button button5 right">Add Medicine</button></a>
	</span>
	<br>
	<br>
	<br>
	<table class="table table-striped table-bordered table-sm">
	<thread class= "thread-dark">
	<tr>
		<th>Medicine ID</th>
		<th>Generic Name</th>
		<th>Title</th>
		<th>Manufacturer</th>
		<th>Nature</th>
		<th>Dose</th>
		<th>Price</th>
		<th>Action</th>
	</tr>
	</thread>
	{% for medicines in medicine %}
	<tr>
		<td>{{ medicines.med_id }}</td>
		<td>{{ medicines.g_name }}</td>
		<td>{{ medicines.m_title }}</td>
		<td>{{ medicines.m_make }}</td>
		<td>{{ medicines.m_nature }}</td>
		<td>{{ medicines.m_doze }}</td>
		<td>{{ medicines.m_sprice }}</td>
		<td>
			<a href="{% url 'phsys:update_med' medicines.med_id %}"><span class="btn btn-success">Edit</span></a>
			<a href="{% url 'phsys:delete_med' medicines.med_id %}" class='btn btn-danger'>Delete</a>
		</td>
	</tr>
	{% endfor %}
	<tbody>
</body>

templates/payment.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
</html>

<head>
	<style>
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;
	  
	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Manufacturer Payment</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
<div >
	<div class="col">
		<div class="card card-body">

			<form method="POST" action="{% url 'phsys:payment' %}">
			{% csrf_token %}
				<div class="well">
					<h4 style="margin-top: 0">Manufacturer Payment</h4><br>

					<div >
					  <div class="form-group col-sm-4 col-md-3">
						Payment Date<input class="input" type="date" name="p_date" placeholder="Payment Date">
					  </div>
					  <div class="form-group col-sm-4 col-md-3">
						Payment Type<br><select type="text" class="form-input" name="p_type" id = "myList" placeholder="Medicine ID"/>
                        <option value = "1">Select</option>
                                   <option value = "Cash">Cash</option>
                                   <option value = "Bank">Bank</option>
                        </select>
					  </div>
					  <div class="form-group col-sm-4 col-md-3">
						Transaction Details<input type="text" class="form-input" name="trdetail" id="name" placeholder="Write here..."/>
					  </div>
					  <div class="form-group col-sm-4 col-md-3">
						Amount<input type="text" class="form-input" name="amount" id="name" placeholder="Amount"/>
					  </div>
					  <div class="form-group col-sm-4 col-md-3">
						Manufacturer<select type="text" class="form-input" name="make" id = "myList" placeholder="Medicine ID"/>
                        <option value = "1">Select</option>
                                   {% for medid in data %}
                                   <option value = "{{medid.party_id}}">{{medid.par_name}}</option>
                                   {% endfor %}
                        </select>
                        <br><br><button class="btn btn-primary" type="submit">Save</button>
					  </div>

		    		
		  </form>

		</div>
	</div>
	
</div>
<br>
</body>

templates/sale.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
</html>

<head>
	<style>
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;

	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Medicine List</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
</head>
<body>
{% include "index.html" %}
        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5 pt-5">
			<span><br>
			<h1>Manage Sale</h1>
			<!--<a href="addmed"><button class="button button5 right">Add Medicine</button></a>-->
			</span>
			<br>
			<table class="table table-striped table-bordered table-sm ">
			<thread class= "thread-dark">
			<tr>
				<th>Bill No.</th>
				<th>Date of Sale</th>
				<th>Customer ID</th>
				<th>Action</th>
				<th>Download Purchase Detail</th>
			</tr>
			</thread>
			{% for sal in data %}
			<tr>
				<td>{{ sal.sbillno }}</td>
				<td>{{ sal.s_date }}</td>
				<td>{{ sal.cidfk }}</td>
				<td>
					<a href="{% url 'phsys:sale-detail' id=sal.sbillno %}"><span class="btn btn-success">Sale Detail</span></a>
					<a href="{% url 'phsys:delete_sale' sal.sbillno %}" class='btn btn-danger'>Delete</a>
				</td>
				<td width="#"><a href="{% url 'phsys:sale-download' id=sal.sbillno %}">Download</a></td>
			</tr>
			{% endfor %}
			<tbody>
</body>

templates/updatecus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update Customer</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'login/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
</head>
<body>
    <div class="main">
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                            <form method="POST" id="signup-form" class="signup-form" action="/update_cus/{{cus.cusid}}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-input" value={{cus.cusid}} name="cus_id" id="name" placeholder="Customer ID" readonly/>
                                </div>

                                <div class="form-group">
                                    <input type="text" class="form-input" value={{cus.cus_name}} name="cus_name" id="name" placeholder="Name"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-input" value={{cus.cus_address}} name="cus_address" id="name" placeholder="Address"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-input" value={{cus.cus_contact}} name="cus_contact" id="contact" placeholder="Contact Number"/>
                                </div>
                                 <div class="form-group">
                                    <input type="text" class="form-input" value={{cus.cus_email}} name="cus_email" id="email" placeholder="Email Address"/>
                                </div>
                                <div class="form-group">
                                    <input type="submit" name="submit" id="submit" class="form-submit" value="Update"/>
                                </div>
                                <div>
                                    {% for message in messages %}
                                    <h3><center>{{message}} </center> </h3>
                                    {% endfor %}
                                </div>
                            </form>
                    <p class="loginhere">
                        <a href="{% url 'phsys:customer' %}" class="loginhere-link">Go back</a>
                    </p>
                </div>
            </div>
        </section>

    </div>
    <!-- JS -->
    <script src="{% static 'login/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'login/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

templates/users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


     <style>
	.right {
	  position: absolute;
  	  right: 40px;
	}
	.button {
	  background-color: #4CAF50; /* Green */
	  border: none;
	  color: white;
	  padding: 14px 25px;
	  text-align: center;
	  text-decoration: none;
	  display: inline-block;
	  font-size: 16px;
	  margin: 4px 2px;
	  transition-duration: 0.4s;
	  cursor: pointer;
	}

	.button5 {
	  border-radius: 4px;
	  background-color: #555555;
	  color: white;
	  
	}

	.button5:hover {
	  border-radius: 4px;
	  background-color: white;
	  color: black;
	  border: 2px solid #555555;
	}

	</style>
	<meta charset="UTF-8">
	<title>Users List</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
<head>
<body>
{% include "index.html" %}
	<span><br>
	<h1>Users List</h1>
	<a href="adduser"><button class="button button5 right">New User</button></a>
	</span>
<form action="{% url 'phsys:users' %}" method="post">{% csrf_token %}<br>
	<br>
	<br>
	<br>
	<table class="table table-striped table-bordered table-sm">
	<thread class= "thread-dark">
	<tr>
		<th></th>
		<th>User ID</th>
		<th>Username</th>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Email Address</th>
		<th>Date Joined</th>
		<th>Status</th>
		<th>Action</th>
	</tr>
	</thread>
	{% for users in user %}
	<tr>
		<td><input class="checkbox" type="checkbox" value="{{users.id}}" name="user_id" size="1" />
    	</td>
    	<td>{{ users.id }}</td>
		<td>{{ users.username }}</td>
		<td>{{ users.first_name }}</td>
		<td>{{ users.last_name }}</td>
		<td>{{ users.email }}</td>
		<td>{{ users.date_joined }}</td>
		<td>{{ users.name}}</td>
		<!--<td>{{ users.name }}</td>-->
		<td>
			<a href="{% url 'phsys:delete_user' users.username %}" class='btn btn-danger'>Delete</a>
		</td>
	</tr>
{% endfor %}

	</table>
	 <div class="select is-rounded">
        <select id="status" name="status">
            <option value="1">Admin</option>
            <option value="2">Manager</option>
            <option value="3">Sales Person</option>
            <option value="null">None</option>
        </select>
    </div>
    <input class="button is-info is-rounded btn-work2" type="submit" value="Change Status" name="mybtn">
</form>
</body>
</head>